version: "3.3"

services:
  java:
    build: .
    container_name: springbootapp
    ports:
      - "80:80"
    networks:
      - app-network
    env_file:
      - env/javadatabase.env
    volumes:
      - ./target/dependency/project:/app
    depends_on:
      - database

  database:
    container_name: DB
    image: 'docker.io/bitnami/postgresql:13-debian-10'
    env_file:
      - env/pgdatabase.env
    ports:
      - 5432:5432
    networks:
    - app-network
  #Docker Networks
networks:
  app-network:
    driver: bridge